apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  annotations:
      keda.sh/namespace: argo-hpa
  name: http-scaler
  namespace: argo-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: http
  minReplicaCount: 2
  maxReplicaCount: 4
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleUp:
          stabilizationWindowSeconds: 15
          policies:
            - type: Percent
              value: 100
              periodSeconds: 15
        scaleDown:
          stabilizationWindowSeconds: 60
          policies:
            - type: Percent
              value: 50
              periodSeconds: 60
  triggers:
    - type: cpu
      metricType: Utilization
      metadata:
        value: "80"
    - type: memory
      metricType: Utilization
      metadata:
        value: "80"
