apiVersion: apps/v1
kind: Deployment
metadata:
  name: http
  namespace: argo-hpa
  labels:
    app: http
spec:
  selector:
    matchLabels:
      app: http
  template:
    metadata:
      labels:
        app: http
    spec:
      containers:
        - name: app
          image: nginx:stable
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          ports:
            - containerPort: 80
